### ISSUE TITLE
Readme Error

### ISSUE THREAD

**Issue by Hoid2** [Patbox/PlayerDataAPI#1]
In the readme the dependency info is wrong. `"eu.pb4:sidebar-api:[TAG]"` should be `"eu.pb4:player-data-api:[TAG]"`.

**Comment by halotroop2288** [comment]
@Hoid2 For future reference, it's super easy to create pull requests for README files. Just click the edit button in the top right of the preview, and change what you need to.
Pull requests get stuff done quicker.

**Comment by Hoid2** [comment]
@halotroop2288 
Thanks, I didn't know I could  do that. I will do so in the future.
